# III. Working with arrays

Julia has built-in functions that can be used to create arrays of random numbers. We can use the `rand` function to generate random floats between 0 and 1.

In [1]:
a = rand( 20 );
show( a )

[0.13492353595056983, 0.3616613546040821, 0.33037984725495817, 0.45527587317404494, 0.5902375734729657, 0.151989414230288, 0.25065880206638647, 0.04314980177844219, 0.27242082504181653, 0.28572285305544654, 0.2652364704171979, 0.3488129187576403, 0.8899066473492709, 0.19430386913967657, 0.6368815093471398, 0.011579575248139795, 0.11789255437986901, 0.7788698128484988, 0.7273067020090653, 0.3808014404213913]

In [2]:
typeof( a )

Array{Float64,1}

Here we use indexing to get the first three elements of __a__.

In [3]:
a[ 1 : 3 ]

3-element Array{Float64,1}:
 0.13492353595056983
 0.3616613546040821 
 0.33037984725495817

And to get the fourteenth element through the last element __a__:

In [4]:
a[ 14 : end ]

7-element Array{Float64,1}:
 0.19430386913967657 
 0.6368815093471398  
 0.011579575248139795
 0.11789255437986901 
 0.7788698128484988  
 0.7273067020090653  
 0.3808014404213913  

You can use a stride index to get skip over elements in the array. For example to get every other element of __a__ starting with the second element.

In [5]:
show( a[ 2 : 2 : end ] )

[0.3616613546040821, 0.45527587317404494, 0.151989414230288, 0.04314980177844219, 0.28572285305544654, 0.3488129187576403, 0.19430386913967657, 0.011579575248139795, 0.7788698128484988, 0.3808014404213913]

Unlike tuples, arrays are mutable; so we can add and remove elements; `pop!` removes the last element and `push!` can be used to append elements.

In [6]:
pop!( a )

0.3808014404213913

Now, as expected, the array a has 19 elements instead of 20:

In [7]:
length( a )

19

In [8]:
show( a )

[0.13492353595056983, 0.3616613546040821, 0.33037984725495817, 0.45527587317404494, 0.5902375734729657, 0.151989414230288, 0.25065880206638647, 0.04314980177844219, 0.27242082504181653, 0.28572285305544654, 0.2652364704171979, 0.3488129187576403, 0.8899066473492709, 0.19430386913967657, 0.6368815093471398, 0.011579575248139795, 0.11789255437986901, 0.7788698128484988, 0.7273067020090653]

In [9]:
show( push!( a, rand() ) )

[0.13492353595056983, 0.3616613546040821, 0.33037984725495817, 0.45527587317404494, 0.5902375734729657, 0.151989414230288, 0.25065880206638647, 0.04314980177844219, 0.27242082504181653, 0.28572285305544654, 0.2652364704171979, 0.3488129187576403, 0.8899066473492709, 0.19430386913967657, 0.6368815093471398, 0.011579575248139795, 0.11789255437986901, 0.7788698128484988, 0.7273067020090653, 0.06754629689440073]

Julia provides set operations that can be applied to arrays. Let's look at three fundamental ones: `union`, `intersect`, and `setdiff`.

In [10]:
a = [ 1, 2, 3, 4, 5, 6 ]; b = [ 4, 5, 6, 7, 8, 9 ];

In [11]:
show( union( a, b ) )

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
show( intersect( a, b ) )

[4, 5, 6]

In [13]:
show( setdiff( a, b ) ) #returns the elements of a that are not in b

[1, 2, 3]

In [14]:
show( setdiff( b, a ) ) #returns the elements of b that are not in a

[7, 8, 9]

There are a few very  useful functions Julia provides that are easy to understand in the context of one dimensional arrays: `map`, `filter`, `reduce`, `mapreduce`.

In [15]:
a = randn( 15 )
show( a )

[0.3865734808693367, -0.30787100340919277, 0.07184901592615978, -0.12393733880877482, -0.10024496255345881, 0.31011315034497594, -1.6561974510858837, 0.06812118072651457, -0.5955123853347581, 0.8441942037104464, 0.34327631941647785, 0.2182667249169342, 0.40480897675582417, 0.12291334480102721, 0.7626899004621648]

The `map` function will apply a function elemenwise to an array. Here we take the exponential of every element of __a__. The first argument to `map` is the function you want to apply to every element in the second object. The function can be an anonymous function, a user-defined function, a built-in function, etc.

In [16]:
exp_a = map( exp, a )
show( exp_a )

[1.4719285516822687, 0.7350101256944266, 1.0744931004704004, 0.8834351962501834, 0.9046157938974881, 1.3635793948824861, 0.19086336926359637, 1.0704950239838427, 0.5512800256887811, 2.3261026942690424, 1.4095581964181432, 1.2439188075160545, 1.4990161257821475, 1.1307864281788296, 2.144035713449181]

The `filter` function will only return elements that satisfy a specified condition. Here we return elements of __a__ greater than zero.

In [17]:
filt_a = filter( x -> x > 0, a )
show( filt_a )

[0.3865734808693367, 0.07184901592615978, 0.31011315034497594, 0.06812118072651457, 0.8441942037104464, 0.34327631941647785, 0.2182667249169342, 0.40480897675582417, 0.12291334480102721, 0.7626899004621648]

You can apply a reduction operation using `reduce`. Here we apply `reduce` to an array using the multiplication operator:

In [18]:
red_a = reduce( *, a )

-5.313278299194209e-9

You can easily combine the `map` and `reduce` functions in Julia by using the `mapreduce` function. In what follows, the first argument does the map (i.e. square each element in __a__), and the second argument specifies the type of reduction to be applied (i.e. sum), and the last argument specifies what the `mapreduce` is being applied to.

In [19]:
eucnormsq = mapreduce( x -> x ^ 2, +, a )

5.112047798276117

There is also a useful `|>` operator that can be used to pass the result of one function as input to another function. For example, we can rewrite the above expression for __eucnormsq__ using this "pipe-greater-than" syntax:

In [20]:
eucnormsq = map( x -> x ^ 2, a ) |> sum

5.112047798276117

What we did above first was to apply the mapping to __a__ (i.e. squaring each element of __a__) and then we passed the result of `map` as input into the `sum` function which summed up the squared elements.

In Julia, you'll likely often be working with multidimensional arrays.

In [21]:
A = [ 1 2 3; 4 5 6 ]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

Generating random matrices and indexing works the same as before. Below we generate an 8 by 10 matrix of random numbers each distributed according to a standard normal distribution.

In [22]:
A = randn( 8, 10 )

8×10 Array{Float64,2}:
  0.477991   -0.199791    1.4432    …   1.3439     -0.996449    0.93196  
  1.14903    -0.173009    0.241412      0.0451831   0.703688    0.883861 
  1.39793     0.847757    1.89612       2.6343     -0.405119    0.964984 
  0.0913294   0.757207    1.05318      -1.0988     -0.202924    0.680431 
 -0.966571    0.66074     0.495949      1.12713    -0.0859766  -1.30234  
 -0.260985    0.0583227   0.779808  …   0.284318    0.427866   -1.30364  
 -0.0304193   0.452116    0.265134      0.100958   -1.71289    -1.48798  
 -1.67281     2.81933    -0.857127      0.827343    0.846928   -0.0330998

If we wanted all the rows but only columns 6 through 10 from our matrix __A__:

In [23]:
A[ :, 6:10 ]

8×5 Array{Float64,2}:
  0.445823    0.413033   1.3439     -0.996449    0.93196  
 -0.436674   -0.827785   0.0451831   0.703688    0.883861 
  1.46062     0.591493   2.6343     -0.405119    0.964984 
 -0.0107746  -0.866847  -1.0988     -0.202924    0.680431 
  0.747915    0.570118   1.12713    -0.0859766  -1.30234  
 -0.501059   -0.644488   0.284318    0.427866   -1.30364  
 -1.75689    -1.28531    0.100958   -1.71289    -1.48798  
  0.0628369  -0.486666   0.827343    0.846928   -0.0330998

If you wanted rows two through four and only columns 1, 4, and 8 through 10 of __A__:

In [24]:
A[ 2:4, union( 1, 4, 8:10 ) ]

3×5 Array{Float64,2}:
 1.14903    -0.341152   0.0451831   0.703688  0.883861
 1.39793     0.33189    2.6343     -0.405119  0.964984
 0.0913294  -2.94939   -1.0988     -0.202924  0.680431

You can also use boolean indexing to extract elements. Here a random 8 x 10 matrix of booleans is generated:

In [25]:
mask = rand( Bool, 8, 10 )

8×10 Array{Bool,2}:
 1  0  1  1  1  1  0  0  1  1
 1  1  1  0  0  0  0  0  1  1
 0  0  1  1  1  1  0  1  0  1
 0  0  1  1  0  1  1  1  1  1
 0  1  1  0  1  0  0  0  0  1
 1  1  1  0  1  0  0  1  1  0
 1  1  1  0  0  0  1  1  0  1
 1  0  1  1  0  0  0  1  0  1

The following statment will return the elements of __A__ that correspond to the elemnts of *mask* that have an entry of *true*.

In [26]:
A[ mask ]

46-element Array{Float64,1}:
  0.4779906004617154  
  1.1490289539040839  
 -0.2609850573252249  
 -0.030419300252597852
 -1.6728100680182765  
 -0.17300938984719688 
  0.6607398127465368  
  0.05832272832829405 
  0.4521161170395089  
  1.4432018651443566  
  0.24141208261687264 
  1.8961186681134268  
  1.0531800212437652  
  ⋮                   
  0.8273434782364287  
 -0.9964485157153411  
  0.7036880203603155  
 -0.20292419629678163 
  0.4278656131968131  
  0.9319602970345279  
  0.8838607801670021  
  0.9649839781962076  
  0.6804312721084427  
 -1.3023382725579222  
 -1.487981704231936   
 -0.033099768327865216

Similarly if you wanted to return the elements of __A__ that were, say, greater than zero you could do something like the following:

In [27]:
A[ A .> 0 ]

45-element Array{Float64,1}:
 0.4779906004617154 
 1.1490289539040839 
 1.3979272377244707 
 0.09132939704719677
 0.8477573545239118 
 0.7572072146997421 
 0.6607398127465368 
 0.05832272832829405
 0.4521161170395089 
 2.8193296060387536 
 1.4432018651443566 
 0.24141208261687264
 1.8961186681134268 
 ⋮                  
 2.6343049336168654 
 1.1271288569792839 
 0.28431807056508257
 0.10095838214604047
 0.8273434782364287 
 0.7036880203603155 
 0.4278656131968131 
 0.8469278365525964 
 0.9319602970345279 
 0.8838607801670021 
 0.9649839781962076 
 0.6804312721084427 

Note the dot notation used above which is necessary here to do an element-wise comparison.

One thing to be aware of when you do an assignment with arrays is that the new array is actually a *view* of the original array.

In [28]:
B = A

8×10 Array{Float64,2}:
  0.477991   -0.199791    1.4432    …   1.3439     -0.996449    0.93196  
  1.14903    -0.173009    0.241412      0.0451831   0.703688    0.883861 
  1.39793     0.847757    1.89612       2.6343     -0.405119    0.964984 
  0.0913294   0.757207    1.05318      -1.0988     -0.202924    0.680431 
 -0.966571    0.66074     0.495949      1.12713    -0.0859766  -1.30234  
 -0.260985    0.0583227   0.779808  …   0.284318    0.427866   -1.30364  
 -0.0304193   0.452116    0.265134      0.100958   -1.71289    -1.48798  
 -1.67281     2.81933    -0.857127      0.827343    0.846928   -0.0330998

In [29]:
isequal( B, A )

true

The `===` tests if __B__ and __A__ point to the same location in memory:

In [30]:
B === A

true

Now let's change some elements of __B__. What do you think will happen to __A__?

In [31]:
B[ 1, 1:end ] .= 999;

In [32]:
B

8×10 Array{Float64,2}:
 999.0        999.0        999.0       …  999.0        999.0      
   1.14903     -0.173009     0.241412       0.703688     0.883861 
   1.39793      0.847757     1.89612       -0.405119     0.964984 
   0.0913294    0.757207     1.05318       -0.202924     0.680431 
  -0.966571     0.66074      0.495949      -0.0859766   -1.30234  
  -0.260985     0.0583227    0.779808  …    0.427866    -1.30364  
  -0.0304193    0.452116     0.265134      -1.71289     -1.48798  
  -1.67281      2.81933     -0.857127       0.846928    -0.0330998

Note that even though we changed the elements of __B__ the elements of the original array __A__ also changed.

In [33]:
A

8×10 Array{Float64,2}:
 999.0        999.0        999.0       …  999.0        999.0      
   1.14903     -0.173009     0.241412       0.703688     0.883861 
   1.39793      0.847757     1.89612       -0.405119     0.964984 
   0.0913294    0.757207     1.05318       -0.202924     0.680431 
  -0.966571     0.66074      0.495949      -0.0859766   -1.30234  
  -0.260985     0.0583227    0.779808  …    0.427866    -1.30364  
  -0.0304193    0.452116     0.265134      -1.71289     -1.48798  
  -1.67281      2.81933     -0.857127       0.846928    -0.0330998

If you want to avoid this behavior then you can use the `copy` function to make a copy of the original array:

In [34]:
C = copy( A );

In [35]:
isequal( C, A )

true

In [36]:
C === A

false

What the above shows is that __C__ points to a different location in memory than __A__, so you can change __C__ without affecting __A__.

Let's move on and look at some basic functions and operations that you can with arrays.

To check the dimension of an array you can use the `ndims` function:

In [37]:
A = randn( 8, 10 )

8×10 Array{Float64,2}:
 -0.467513   -0.380963   0.383493  …   0.420136   0.275116   -1.49788  
  0.173303   -0.279121  -0.272067      0.487355   1.13166    -0.10425  
  1.27625     1.21316    0.273529     -0.912226  -0.0200588  -0.559369 
  1.88922     0.858852   1.03317       0.128306   2.41678    -0.0133431
  0.0797212  -0.204386  -0.19577      -0.120651  -0.339679    0.0574646
  0.277614   -0.655177  -1.2291    …   0.863544  -0.275151    0.0885445
  2.2218      0.232466   0.978386     -1.23424   -1.64764     0.895178 
 -0.933427    0.113479  -0.91557       0.560163  -0.648473    1.5168   

In [38]:
ndims( A )

2

To get the number of rows and columns use `size`:

In [39]:
size( A )

(8, 10)

The `reshape` function will change the shape of the array:

In [40]:
A

8×10 Array{Float64,2}:
 -0.467513   -0.380963   0.383493  …   0.420136   0.275116   -1.49788  
  0.173303   -0.279121  -0.272067      0.487355   1.13166    -0.10425  
  1.27625     1.21316    0.273529     -0.912226  -0.0200588  -0.559369 
  1.88922     0.858852   1.03317       0.128306   2.41678    -0.0133431
  0.0797212  -0.204386  -0.19577      -0.120651  -0.339679    0.0574646
  0.277614   -0.655177  -1.2291    …   0.863544  -0.275151    0.0885445
  2.2218      0.232466   0.978386     -1.23424   -1.64764     0.895178 
 -0.933427    0.113479  -0.91557       0.560163  -0.648473    1.5168   

In [41]:
C = reshape( A, 2, 40 )

2×40 Array{Float64,2}:
 -0.467513  1.27625  0.0797212   2.2218    …  -0.559369   0.0574646  0.895178
  0.173303  1.88922  0.277614   -0.933427     -0.0133431  0.0885445  1.5168  

In [42]:
size( C )

(2, 40)

In [43]:
A = randn( 5, 5 )

5×5 Array{Float64,2}:
 -0.0708218   0.599349  -0.459466  -1.03224    0.748768
 -0.632277   -0.282738  -1.29403   -0.83848   -0.606101
  0.264445    0.377428   0.743642  -0.72129   -2.16191 
  1.18843    -0.4593     1.61646    0.577156   0.292473
 -0.53152    -0.10628   -0.19545   -1.53822   -0.75184 

To extract the diagonal elements of __A__:

In [44]:
using LinearAlgebra #this package contains the diag function and other linear algebra routines

diag( A )

5-element Array{Float64,1}:
 -0.07082178661879042
 -0.28273845074040893
  0.7436423438909697 
  0.5771563779374547 
 -0.7518400621645667 

You can use the following constructor notation to create an identity matrix:

In [45]:
Imatfirst = Array{ Float64 }( I, 5, 5 )

5×5 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0

You can also use **undef** to initialize an array to nothing in particular (some undefined strings or some undefined integers):

In [46]:
InitStringArray = Array{ String }( undef, 5, 5 )

5×5 Array{String,2}:
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef

In [47]:
InitIntArray = Array{ Int64 }( undef, 5, 5 )

5×5 Array{Int64,2}:
 139751752706928  139751752706928  139751752356560  139751752372096  0
 139751752356560  139751752356560  139751752356560  139751467142480  0
 139751752706928  139751752374960  139751752356560  139751752356560  0
 139751752356560  139751752374960  139751752839776                0  0
 139751752374032  139751752356560  139751752356560                0  0

And the `zeros` function will create a matrix of zeros:

In [48]:
zeros( 4, 5 )

4×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

Instead of the `zeros` function another option is to use the `fill` function:

In [49]:
fill( 0.0, ( 5, 5 ) )

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

You can use `fill` to fill the array with any arbitray value (not just zeros).

In [50]:
fill( "foo", ( 5, 5 ) )

5×5 Array{String,2}:
 "foo"  "foo"  "foo"  "foo"  "foo"
 "foo"  "foo"  "foo"  "foo"  "foo"
 "foo"  "foo"  "foo"  "foo"  "foo"
 "foo"  "foo"  "foo"  "foo"  "foo"
 "foo"  "foo"  "foo"  "foo"  "foo"

The __ones__ function will create a matrix of ones:

In [51]:
ones( 5, 5 )

5×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

You can use also the `Diagonal` function with the `ones` function to create an identity matrix:

In [52]:
Imatsec = Diagonal( ones( 5, 5 ) )

5×5 Diagonal{Float64,Array{Float64,1}}:
 1.0   ⋅    ⋅    ⋅    ⋅ 
  ⋅   1.0   ⋅    ⋅    ⋅ 
  ⋅    ⋅   1.0   ⋅    ⋅ 
  ⋅    ⋅    ⋅   1.0   ⋅ 
  ⋅    ⋅    ⋅    ⋅   1.0

We can see that the second method of creating the identity matrix is more storage-efficient:

In [53]:
InteractiveUtils.varinfo()

| name            |      size | summary                                |
|:--------------- | ---------:|:-------------------------------------- |
| A               | 240 bytes | 5×5 Array{Float64,2}                   |
| B               | 680 bytes | 8×10 Array{Float64,2}                  |
| Base            |           | Module                                 |
| C               | 680 bytes | 2×40 Array{Float64,2}                  |
| Core            |           | Module                                 |
| Imatfirst       | 240 bytes | 5×5 Array{Float64,2}                   |
| Imatsec         |  88 bytes | 5×5 Diagonal{Float64,Array{Float64,1}} |
| InitIntArray    | 240 bytes | 5×5 Array{Int64,2}                     |
| InitStringArray | 240 bytes | 5×5 Array{String,2}                    |
| Main            |           | Module                                 |
| a               | 160 bytes | 15-element Array{Float64,1}            |
| b               |  88 bytes | 6-element Array{Int64,1}               |
| eucnormsq       |   8 bytes | Float64                                |
| exp_a           | 160 bytes | 15-element Array{Float64,1}            |
| filt_a          | 120 bytes | 10-element Array{Float64,1}            |
| mask            | 120 bytes | 8×10 Array{Bool,2}                     |
| red_a           |   8 bytes | Float64                                |


And to create a diagonal matrix use `diagm`:

In [54]:
diagm( 0 => [ 1, 2, 8, 9 ] )

4×4 Array{Int64,2}:
 1  0  0  0
 0  2  0  0
 0  0  8  0
 0  0  0  9

The first argument in `diagm` specifies the offset. So if wanted the diagonal to be offset by -1:

In [55]:
diagm( -1 => [ 1, 2, 8, 9 ] )

5×5 Array{Int64,2}:
 0  0  0  0  0
 1  0  0  0  0
 0  2  0  0  0
 0  0  8  0  0
 0  0  0  9  0

As mentioned before, if you want to do element-wise operations on an array you use dot notation. To demonstrate let's first generate a random matrix.

In [56]:
A = randn( 4, 5 )

4×5 Array{Float64,2}:
  0.76591    0.385117    2.00326    0.118398   0.108468 
 -0.550899   0.0551669  -0.782166  -0.836905   0.74461  
 -0.700863  -1.59515    -0.672414  -0.235647  -0.406396 
  0.274919   0.42225     0.062825  -0.447235   0.0153915

Now we square every element of __A__ using the dot syntax:

In [57]:
A.^2

4×5 Array{Float64,2}:
 0.586618   0.148315    4.01306     0.0140181  0.0117654  
 0.30349    0.00304339  0.611784    0.70041    0.554444   
 0.491209   2.54452     0.45214     0.0555293  0.165157   
 0.0755803  0.178295    0.00394698  0.200019   0.000236899

Similarly we can do element-wise division between two matrices. Below we can create a new random matrix __B__ then divide the elements of __A__ by their corresponding elements in __B__.

In [58]:
B =  randn( 4, 5 )

4×5 Array{Float64,2}:
  0.672032   0.479321   1.28393    0.533865  -0.627303
 -1.04185    0.328471  -0.385019  -0.732564   1.02231 
  0.87989    0.150005  -0.401088  -0.123529   0.213244
  0.150085  -1.71791   -0.122684   3.00457   -0.860433

In [59]:
A ./ B

4×5 Array{Float64,2}:
  1.13969     0.803462   1.56026    0.221775  -0.172912 
  0.528768    0.167951   2.0315     1.14243    0.728359 
 -0.796535  -10.634      1.67647    1.90762   -1.90578  
  1.83176    -0.245793  -0.512087  -0.148851  -0.0178881

There are a lot of basic functions that can be applied to arrays: `sum`, `mean`, `sort`, etc.

In [60]:
A = [ [ 1 -1 2 3 ]; [ 4 -3 1 0 ]; [ 7 -3 -3 2 ] ]

3×4 Array{Int64,2}:
 1  -1   2  3
 4  -3   1  0
 7  -3  -3  2

To sum all the elements of **A**:

In [61]:
sum( A )

10

In [62]:
sum( A, dims = 1 ) #sums each column

1×4 Array{Int64,2}:
 12  -7  0  5

In [63]:
sum( A, dims = 2 ) #sums each row

3×1 Array{Int64,2}:
 5
 2
 3

In [64]:
A

3×4 Array{Int64,2}:
 1  -1   2  3
 4  -3   1  0
 7  -3  -3  2

The `sort` function will sort the array along the indicated dimension.

In [65]:
sort( A, dims = 1 ) #sort each column in ascending order

3×4 Array{Int64,2}:
 1  -3  -3  0
 4  -3   1  2
 7  -1   2  3

In [66]:
sort( A, dims= 1, rev=true ) #sort each column in descending order

3×4 Array{Int64,2}:
 7  -1   2  3
 4  -3   1  2
 1  -3  -3  0

In [67]:
A

3×4 Array{Int64,2}:
 1  -1   2  3
 4  -3   1  0
 7  -3  -3  2

In [68]:
sort( A, dims = 2 ) #sort each row in ascending order

3×4 Array{Int64,2}:
 -1   1  2  3
 -3   0  1  4
 -3  -3  2  7

Finally concatenating arrays is a very common operation. You can use the built-ins `hcat` and `vcat` to concatenate arrays. The `vcat` function will concatenate the arrays column wise (i.e. along dimension 1); `hcat` will concatenate arrays row wise (i.e. along dimension 2).

In [69]:
A = [ 1 2; 3 4 ]

2×2 Array{Int64,2}:
 1  2
 3  4

In [70]:
B = [ 5 6; 7 8; 9 10 ]

3×2 Array{Int64,2}:
 5   6
 7   8
 9  10

In [71]:
C = randn( 2, 1 )

2×1 Array{Float64,2}:
 1.7355615224469705
 0.6616088518522533

In [72]:
vcat( A, B )  #stacks A on top of B

5×2 Array{Int64,2}:
 1   2
 3   4
 5   6
 7   8
 9  10

In [73]:
hcat( A, C, A ) #horizontally binds A to C to A

2×5 Array{Float64,2}:
 1.0  2.0  1.73556   1.0  2.0
 3.0  4.0  0.661609  3.0  4.0

# Exercise 3
* Create a 5 by 8 random array called *B* using **randn**.
* Find the elements of *B* that are less than 0.2.
* Retrieve the number of rows and columns of *B*.
* Multiply every element of *B* by 3 and assign that to a new array called *C*.
* Sort each row of *C* in ascending order.

In this lesson we covered:
* Single and multi-dimensional arrays.
* Array indexing.
* Applying functions to arrays.