# IV. Working with arrays

Julia has built-in functions that can be used to create arrays of random numbers. We can use the `rand` function to generate random floats between 0 and 1.

In [1]:
a = rand( 20 );
show( a )

[0.44877900696307305, 0.7936704262800842, 0.9267158138387337, 0.36708606095755325, 0.7119153020028728, 0.4414998373061967, 0.6452066504155047, 0.1246123564332724, 0.9441049562365382, 0.23049116043559081, 0.4966664892376971, 0.3388561092306317, 0.6288411408836008, 0.22396957401674822, 0.46604838387518477, 0.8365740584878163, 0.4200569611135525, 0.19012284206307917, 0.08485042672308629, 0.45788906989978706]

In [2]:
typeof( a )

Array{Float64,1}

Here we use indexing to get the first three elements of __a__.

In [3]:
a[ 1 : 3 ]

3-element Array{Float64,1}:
 0.44877900696307305
 0.7936704262800842 
 0.9267158138387337 

And to get the fourteenth element through the last element __a__:

In [4]:
a[ 14 : end ]

7-element Array{Float64,1}:
 0.22396957401674822
 0.46604838387518477
 0.8365740584878163 
 0.4200569611135525 
 0.19012284206307917
 0.08485042672308629
 0.45788906989978706

You can use a stride index to get skip over elements in the array. For example to get every other element of __a__ starting with the second element.

In [5]:
show( a[ 2 : 2 : end ] )

[0.7936704262800842, 0.36708606095755325, 0.4414998373061967, 0.1246123564332724, 0.23049116043559081, 0.3388561092306317, 0.22396957401674822, 0.8365740584878163, 0.19012284206307917, 0.45788906989978706]

Unlike tuples, arrays are mutable; so we can add and remove elements; `pop!` removes the last element and `push!` can be used to append elements.

In [6]:
pop!( a )

0.45788906989978706

Now, as expected, the array a has 19 elements instead of 20:

In [7]:
length( a )

19

In [8]:
show( a )

[0.44877900696307305, 0.7936704262800842, 0.9267158138387337, 0.36708606095755325, 0.7119153020028728, 0.4414998373061967, 0.6452066504155047, 0.1246123564332724, 0.9441049562365382, 0.23049116043559081, 0.4966664892376971, 0.3388561092306317, 0.6288411408836008, 0.22396957401674822, 0.46604838387518477, 0.8365740584878163, 0.4200569611135525, 0.19012284206307917, 0.08485042672308629]

In [9]:
show( push!( a, rand() ) )

[0.44877900696307305, 0.7936704262800842, 0.9267158138387337, 0.36708606095755325, 0.7119153020028728, 0.4414998373061967, 0.6452066504155047, 0.1246123564332724, 0.9441049562365382, 0.23049116043559081, 0.4966664892376971, 0.3388561092306317, 0.6288411408836008, 0.22396957401674822, 0.46604838387518477, 0.8365740584878163, 0.4200569611135525, 0.19012284206307917, 0.08485042672308629, 0.8666020569988877]

Julia provides set operations that can be applied to arrays. Let's look at three fundamental ones: `union`, `intersect`, and `setdiff`.

In [10]:
a = [ 1, 2, 3, 4, 5, 6 ]; b = [ 4, 5, 6, 7, 8, 9 ];

In [11]:
show( union( a, b ) )

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
show( intersect( a, b ) )

[4, 5, 6]

In [13]:
show( setdiff( a, b ) ) #returns the elements of a that are not in b

[1, 2, 3]

In [14]:
show( setdiff( b, a ) ) #returns the elements of b that are not in a

[7, 8, 9]

There are a few very  useful functions Julia provides that are easy to understand in the context of one dimensional arrays: `map`, `filter`, `reduce`, `mapreduce`.

In [15]:
a = randn( 15 )
show( a )

[-0.08736943654326527, 1.2008428824882467, -1.0380568433458843, -1.4424867534562946, 1.0182011983903962, 1.1744290705623008, -0.7319175597411494, 0.8134710472817097, 1.0813557913013216, 1.1326299890309812, -0.9191339605060089, -0.3851286518569696, 0.4890783294842087, 1.6625284383497025, 1.0762105248921472]

The `map` function will apply a function elemenwise to an array. Here we take the exponential of every element of __a__. The first argument to `map` is the function you want to apply to every element in the second object. The function can be an anonymous function, a user-defined function, a built-in function, etc.

In [16]:
exp_a = map( exp, a )
show( exp_a )

[0.9163385041635332, 3.3229165708710955, 0.3541421675056936, 0.23633930972630873, 2.7682108206656215, 3.236294720360645, 0.48098578624405935, 2.255724138852515, 2.948674629620445, 3.1038087582394454, 0.39886432380585657, 0.6803631005975936, 1.630812455317214, 5.272625513245217, 2.933541877502713]

The `filter` function will only return elements that satisfy a specified condition. Here we return elements of __a__ greater than zero.

In [17]:
filt_a = filter( x -> x > 0, a )
show( filt_a )

[1.2008428824882467, 1.0182011983903962, 1.1744290705623008, 0.8134710472817097, 1.0813557913013216, 1.1326299890309812, 0.4890783294842087, 1.6625284383497025, 1.0762105248921472]

You can apply a reduction operation using `reduce`. Here we apply `reduce` to an array using the multiplication operator:

In [18]:
red_a = reduce( *, a )

0.042435507793560784

You can easily combine the `map` and `reduce` functions in Julia by using the `mapreduce` function. In what follows, the first argument does the map (i.e. square each element in __a__), and the second argument specifies the type of reduction to be applied (i.e. sum), and the last argument specifies what the `mapreduce` is being applied to.

In [19]:
eucnormsq = mapreduce( x -> x .^ 2, +, a )

15.828182741838235

There is also a useful `|>` operator that can be used to pass the result of one function as input to another function. For example, we can rewrite the above expression for __eucnormsq__ using this "pipe-greater-than" syntax:

In [20]:
eucnormsq = map( x -> x .^ 2, a ) |> sum

15.828182741838235

What we did above first was to apply the mapping to __a__ (i.e. squaring each element of __a__) and then we passed the result of `map` as input into the `sum` function which summed up the squared elements.

In Julia, you'll likely often be working with multidimensional arrays.

In [21]:
A = [ 1 2 3; 4 5 6 ]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

Generating random matrices and indexing works the same as before. Below we generate an 8 by 10 matrix of random numbers each distributed according to a standard normal distribution.

In [22]:
A = randn( 8, 10 )

8×10 Array{Float64,2}:
 -0.588199    0.508736  -0.315687   …  -1.52769   -1.38732     0.437243
 -1.85296    -0.746307   0.802075      -0.22689   -0.0348382   0.53243 
 -0.422392    0.338332  -0.521169       0.689905  -0.0516263   1.08575 
  0.0647098  -0.103786  -0.79385        0.372748  -0.501954   -0.579264
 -1.13567    -0.820341  -0.0477963     -0.211086   0.525189   -1.32521 
 -0.569856   -0.503512  -0.669074   …   0.665823  -0.0617773  -0.817578
 -1.77331    -1.28219   -0.637752       1.47413   -1.48747     0.567045
  0.627725    0.190829  -0.0993516     -0.445241  -0.488682   -0.490446

If we wanted all the rows but only columns 6 through 10 from our matrix __A__:

In [23]:
A[ :, 6:10 ]

8×5 Array{Float64,2}:
  0.151813   1.09543    -1.52769   -1.38732     0.437243
 -1.02472   -0.497236   -0.22689   -0.0348382   0.53243 
 -1.31035    0.0910516   0.689905  -0.0516263   1.08575 
  0.380908   0.730425    0.372748  -0.501954   -0.579264
 -2.34779   -1.40642    -0.211086   0.525189   -1.32521 
  0.712119  -0.602732    0.665823  -0.0617773  -0.817578
 -0.983387  -0.771777    1.47413   -1.48747     0.567045
 -2.41868   -0.131703   -0.445241  -0.488682   -0.490446

If you wanted rows two through four and only columns 1, 4, and 8 through 10 of __A__:

In [24]:
A[ 2:4, union( 1, 4, 8:10 ) ]

3×5 Array{Float64,2}:
 -1.85296     0.583753  -0.22689   -0.0348382   0.53243 
 -0.422392    0.841061   0.689905  -0.0516263   1.08575 
  0.0647098  -1.55177    0.372748  -0.501954   -0.579264

You can also use boolean indexing to extract elements. Here a random 8 x 10 matrix of booleans is generated:

In [25]:
mask = rand( Bool, 8, 10 )

8×10 Array{Bool,2}:
 0  0  0  0  1  0  1  1  1  0
 0  1  1  0  1  1  1  1  1  0
 0  0  1  0  0  1  1  0  0  0
 0  1  1  0  0  1  0  1  0  0
 1  0  1  0  1  0  0  1  1  1
 0  0  1  1  1  1  0  0  1  0
 0  1  1  0  1  1  0  0  1  1
 1  0  0  0  0  1  1  0  1  0

The following statment will return the elements of __A__ that correspond to the elemnts of *mask* that have an entry of *true*.

In [26]:
A[ mask ]

39-element Array{Float64,1}:
 -1.1356743070076596  
  0.6277245374664063  
 -0.7463070930743725  
 -0.10378602521262978 
 -1.2821932036013308  
  0.8020746619228268  
 -0.5211687702121729  
 -0.7938495316505502  
 -0.04779625050838757 
 -0.6690740711978157  
 -0.6377516240447425  
  0.35167560741310283 
 -0.5218183184121616  
  ⋮                   
 -1.5276915073206048  
 -0.2268895543743474  
  0.37274831589572605 
 -0.21108560701288182 
 -1.3873192039687594  
 -0.03483820536834337 
  0.525188860085896   
 -0.061777314536231406
 -1.4874721879837254  
 -0.48868235563773477 
 -1.325212748162028   
  0.5670453050900165  

Similarly if you wanted to return the elements of __A__ that were, say, greater than zero you could do something like the following:

In [27]:
A[ A .> 0 ]

29-element Array{Float64,1}:
 0.06470982293838486
 0.6277245374664063 
 0.5087361180948782 
 0.33833179717318645
 0.19082879476359424
 0.8020746619228268 
 0.5837529013771592 
 0.8410608269101094 
 0.35167560741310283
 1.4923986716798805 
 1.1685512854634479 
 0.1923467107514815 
 1.7017634086965716 
 ⋮                  
 1.0954318301352897 
 0.09105160727135597
 0.7304253988727584 
 0.6899049520938172 
 0.37274831589572605
 0.6658225044980725 
 1.4741252922268775 
 0.525188860085896  
 0.43724263459727586
 0.5324300136334096 
 1.0857491605689906 
 0.5670453050900165 

Note the dot notation used above which is necessary here to do an element-wise comparison.

One thing to be aware of when you do an assignment with arrays is that the new array is actually a *view* of the original array.

In [28]:
B = A

8×10 Array{Float64,2}:
 -0.588199    0.508736  -0.315687   …  -1.52769   -1.38732     0.437243
 -1.85296    -0.746307   0.802075      -0.22689   -0.0348382   0.53243 
 -0.422392    0.338332  -0.521169       0.689905  -0.0516263   1.08575 
  0.0647098  -0.103786  -0.79385        0.372748  -0.501954   -0.579264
 -1.13567    -0.820341  -0.0477963     -0.211086   0.525189   -1.32521 
 -0.569856   -0.503512  -0.669074   …   0.665823  -0.0617773  -0.817578
 -1.77331    -1.28219   -0.637752       1.47413   -1.48747     0.567045
  0.627725    0.190829  -0.0993516     -0.445241  -0.488682   -0.490446

In [29]:
isequal( B, A )

true

The `===` tests if __B__ and __A__ point to the same location in memory:

In [30]:
B === A

true

Now let's change some elements of __B__. What do you think will happen to __A__?

In [31]:
B[ 1, 1:end ] .= 999;

In [32]:
B

8×10 Array{Float64,2}:
 999.0        999.0       999.0        …  999.0       999.0        999.0     
  -1.85296     -0.746307    0.802075       -0.22689    -0.0348382    0.53243 
  -0.422392     0.338332   -0.521169        0.689905   -0.0516263    1.08575 
   0.0647098   -0.103786   -0.79385         0.372748   -0.501954    -0.579264
  -1.13567     -0.820341   -0.0477963      -0.211086    0.525189    -1.32521 
  -0.569856    -0.503512   -0.669074   …    0.665823   -0.0617773   -0.817578
  -1.77331     -1.28219    -0.637752        1.47413    -1.48747      0.567045
   0.627725     0.190829   -0.0993516      -0.445241   -0.488682    -0.490446

Note that even though we changed the elements of __B__ the elements of the original array __A__ also changed.

In [33]:
A

8×10 Array{Float64,2}:
 999.0        999.0       999.0        …  999.0       999.0        999.0     
  -1.85296     -0.746307    0.802075       -0.22689    -0.0348382    0.53243 
  -0.422392     0.338332   -0.521169        0.689905   -0.0516263    1.08575 
   0.0647098   -0.103786   -0.79385         0.372748   -0.501954    -0.579264
  -1.13567     -0.820341   -0.0477963      -0.211086    0.525189    -1.32521 
  -0.569856    -0.503512   -0.669074   …    0.665823   -0.0617773   -0.817578
  -1.77331     -1.28219    -0.637752        1.47413    -1.48747      0.567045
   0.627725     0.190829   -0.0993516      -0.445241   -0.488682    -0.490446

If you want to avoid this behavior then you can use the `copy` function to make a copy of the original array:

In [34]:
C = copy( A );

In [35]:
isequal( C, A )

true

In [36]:
C === A

false

What the above shows is that __C__ points to a different location in memory than __A__, so you can change __C__ without affecting __A__.

Let's move on and look at some basic functions and operations that you can with arrays.

To check the dimension of an array you can use the `ndims` function:

In [37]:
A = randn( 8, 10 )

8×10 Array{Float64,2}:
 -1.95188     -0.0816066    0.4384    …  -1.07196   -0.0778129  -0.38467 
  1.17609     -1.29499      0.577672     -1.25547   -1.8293     -0.493723
  0.138667     0.284758     0.424024      0.33914    0.326522    0.255978
 -0.684507     0.00122526  -0.192306      0.316041   0.878248    1.58922 
 -0.00497321  -1.98451      0.721935      0.295627  -1.16123     0.360864
  1.35618     -1.04538      0.667371  …   0.782706  -2.55182     0.150979
 -0.528216     0.37271      0.528102      2.02898   -1.25974     0.425167
  0.0312497    0.424725    -0.886063     -0.2991     0.0482524  -1.63073 

In [38]:
ndims( A )

2

To get the number of rows and columns use `size`:

In [39]:
size( A )

(8, 10)

The `reshape` function will change the shape of the array:

In [40]:
A

8×10 Array{Float64,2}:
 -1.95188     -0.0816066    0.4384    …  -1.07196   -0.0778129  -0.38467 
  1.17609     -1.29499      0.577672     -1.25547   -1.8293     -0.493723
  0.138667     0.284758     0.424024      0.33914    0.326522    0.255978
 -0.684507     0.00122526  -0.192306      0.316041   0.878248    1.58922 
 -0.00497321  -1.98451      0.721935      0.295627  -1.16123     0.360864
  1.35618     -1.04538      0.667371  …   0.782706  -2.55182     0.150979
 -0.528216     0.37271      0.528102      2.02898   -1.25974     0.425167
  0.0312497    0.424725    -0.886063     -0.2991     0.0482524  -1.63073 

In [41]:
C = reshape( A, 2, 40 ) 

2×40 Array{Float64,2}:
 -1.95188   0.138667  -0.00497321  …  0.255978  0.360864   0.425167
  1.17609  -0.684507   1.35618        1.58922   0.150979  -1.63073 

In [42]:
size( C )

(2, 40)

In [43]:
A = randn( 5, 5 )

5×5 Array{Float64,2}:
 0.203911  -0.279593  -0.181858   0.467662    0.113495
 0.273492  -0.231788  -2.03255    0.0105262  -1.17258 
 0.9423     1.54596    0.634344   0.261695   -0.565768
 1.75327   -0.504753   0.998413  -0.599146   -0.161763
 1.53071    0.314562   1.22407    1.71312    -0.575229

To extract the diagonal elements of __A__:

In [44]:
using LinearAlgebra #this package contains the diag function and other linear algebra routines

diag( A )

5-element Array{Float64,1}:
  0.20391145583121495
 -0.23178837489855234
  0.6343436963409214 
 -0.5991463837762768 
 -0.5752289732868803 

You can use the following constructor notation to create an identity matrix:

In [45]:
Imatfirst = Array{ Float64 }( I, 5, 5 )

5×5 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0

You can also use **undef** to initialize an array to nothing in particular (some undefined strings or some undefined integers):

In [46]:
InitStringArray = Array{ String }( undef, 5, 5 )

5×5 Array{String,2}:
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef

In [47]:
InitIntArray = Array{ Int64 }( undef, 5, 5 )

5×5 Array{Int64,2}:
 139828469329792  139828469332656  …  139828469332656  139828469314256
 139828469664624  139828469329792     139828469314256  139828469314256
 139828469314256  139828469664624     139828469664240  139828469331728
 139828470532352  139828469329792     139828469314256  139828469314256
 139828469332656  139828470362352     139828469314256  139828469314256

And the `zeros` function will create a matrix of zeros:

In [48]:
zeros( 4, 5 )

4×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

Instead of the `zeros` function another option is to use the `fill` function:

In [49]:
fill( 0.0, ( 5, 5 ) )

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

You can use `fill` to fill the array with any arbitray value (not just zeros).

In [50]:
fill( "foo", ( 5, 5 ) )

5×5 Array{String,2}:
 "foo"  "foo"  "foo"  "foo"  "foo"
 "foo"  "foo"  "foo"  "foo"  "foo"
 "foo"  "foo"  "foo"  "foo"  "foo"
 "foo"  "foo"  "foo"  "foo"  "foo"
 "foo"  "foo"  "foo"  "foo"  "foo"

The __ones__ function will create a matrix of ones:

In [51]:
ones( 5, 5 )

5×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

You can use also the `Diagonal` function with the `ones` function to create an identity matrix:

In [52]:
Imatsec = Diagonal( ones( 5, 5 ) )

5×5 Diagonal{Float64,Array{Float64,1}}:
 1.0   ⋅    ⋅    ⋅    ⋅ 
  ⋅   1.0   ⋅    ⋅    ⋅ 
  ⋅    ⋅   1.0   ⋅    ⋅ 
  ⋅    ⋅    ⋅   1.0   ⋅ 
  ⋅    ⋅    ⋅    ⋅   1.0

We can see that the second method of creating the identity matrix is more storage-efficient:

In [53]:
InteractiveUtils.varinfo()

| name            |      size | summary                                |
|:--------------- | ---------:|:-------------------------------------- |
| A               | 240 bytes | 5×5 Array{Float64,2}                   |
| B               | 680 bytes | 8×10 Array{Float64,2}                  |
| Base            |           | Module                                 |
| C               | 680 bytes | 2×40 Array{Float64,2}                  |
| Core            |           | Module                                 |
| Imatfirst       | 240 bytes | 5×5 Array{Float64,2}                   |
| Imatsec         |  88 bytes | 5×5 Diagonal{Float64,Array{Float64,1}} |
| InitIntArray    | 240 bytes | 5×5 Array{Int64,2}                     |
| InitStringArray | 240 bytes | 5×5 Array{String,2}                    |
| Main            |           | Module                                 |
| a               | 160 bytes | 15-element Array{Float64,1}            |
| b               |  88 bytes | 6-element Array{Int64,1}               |
| eucnormsq       |   8 bytes | Float64                                |
| exp_a           | 160 bytes | 15-element Array{Float64,1}            |
| filt_a          | 112 bytes | 9-element Array{Float64,1}             |
| mask            | 120 bytes | 8×10 Array{Bool,2}                     |
| red_a           |   8 bytes | Float64                                |


And to create a diagonal matrix use `diagm`:

In [54]:
diagm( 0 => [ 1, 2, 8, 9 ] )

4×4 Array{Int64,2}:
 1  0  0  0
 0  2  0  0
 0  0  8  0
 0  0  0  9

The first argument in `diagm` specifies the offset. So if wanted the diagonal to be offset by -1:

In [55]:
diagm( -1 => [ 1, 2, 8, 9 ] )

5×5 Array{Int64,2}:
 0  0  0  0  0
 1  0  0  0  0
 0  2  0  0  0
 0  0  8  0  0
 0  0  0  9  0

As mentioned before, if you want to do element-wise operations on an array you use dot notation. To demonstrate let's first generate a random matrix.

In [56]:
A = randn( 4, 5 )

4×5 Array{Float64,2}:
 -2.58148    -0.0831368   0.656043    0.718383  -0.126448
  0.572138   -1.6537     -0.0901001   1.28999    0.665111
 -0.333823    1.36829     1.37602    -0.565062   0.473332
 -0.0761523   1.05702    -0.340291    0.243984  -2.2076  

Now we square every element of __A__:

In [57]:
A.^2

4×5 Array{Float64,2}:
 6.66404     0.00691172  0.430392    0.516074   0.0159892
 0.327342    2.73473     0.00811804  1.66406    0.442373 
 0.111438    1.87221     1.89344     0.319295   0.224044 
 0.00579917  1.1173      0.115798    0.0595284  4.87348  

Similarly we can do element-wise division between two matrices. Below we can create a new random matrix __B__ then divide the elements of __A__ by their corresponding elements in __B__.

In [58]:
B =  randn( 4, 5 )

4×5 Array{Float64,2}:
  0.886945    0.226192  -1.07142     1.80518   -0.388993
 -0.491382   -0.460997   1.17666    -1.11152    1.60572 
 -0.0956587  -0.273964  -0.0120846  -0.194455  -1.30249 
  1.11621     1.53942   -0.253041   -1.13783    1.01172 

In [59]:
A ./ B

4×5 Array{Float64,2}:
 -2.91053    -0.36755     -0.612311    0.397956   0.325066
 -1.16435     3.58723     -0.0765728  -1.16056    0.414215
  3.48973    -4.9944    -113.865       2.90587   -0.363406
 -0.0682238   0.686638     1.3448     -0.214429  -2.18202 

There are a lot of basic functions that can be applied to arrays: `sum`, `mean`, `sort`, etc.

In [60]:
A = [ [ 1 -1 2 3 ]; [ 4 -3 1 0 ]; [ 7 -3 -3 2 ] ]

3×4 Array{Int64,2}:
 1  -1   2  3
 4  -3   1  0
 7  -3  -3  2

To sum all the elements of **A**:

In [61]:
sum( A )

10

In [62]:
sum( A, dims = 1 ) #sums each column

1×4 Array{Int64,2}:
 12  -7  0  5

In [63]:
sum( A, dims = 2 ) #sums each row

3×1 Array{Int64,2}:
 5
 2
 3

In [64]:
A

3×4 Array{Int64,2}:
 1  -1   2  3
 4  -3   1  0
 7  -3  -3  2

The `sort` function will sort the array along the indicated dimension.

In [65]:
sort( A, dims = 1 ) #sort each column in ascending order

3×4 Array{Int64,2}:
 1  -3  -3  0
 4  -3   1  2
 7  -1   2  3

In [66]:
sort( A, dims= 1, rev=true ) #sort each column in descending order

3×4 Array{Int64,2}:
 7  -1   2  3
 4  -3   1  2
 1  -3  -3  0

In [67]:
sort( A, dims = 2 ) #sort each row in ascending order

3×4 Array{Int64,2}:
 -1   1  2  3
 -3   0  1  4
 -3  -3  2  7

Finally concatenating arrays is a very common operation. You can use the built-ins `hcat` and `vcat` to concatenate arrays. The `vcat` function will concatenate the arrays column wise (i.e. along dimension 1); `hcat` will concatenate arrays row wise (i.e. along dimension 2).

In [68]:
A = [ 1 2; 3 4 ]

2×2 Array{Int64,2}:
 1  2
 3  4

In [69]:
B = [ 5 6; 7 8; 9 10 ]

3×2 Array{Int64,2}:
 5   6
 7   8
 9  10

In [70]:
C = randn( 2, 1 )

2×1 Array{Float64,2}:
 0.32589722558465933
 0.4199911856392345 

In [71]:
vcat( A, B )  #stacks A on top of B

5×2 Array{Int64,2}:
 1   2
 3   4
 5   6
 7   8
 9  10

In [72]:
hcat( A, C, A ) #horizontally binds A to C to A

2×5 Array{Float64,2}:
 1.0  2.0  0.325897  1.0  2.0
 3.0  4.0  0.419991  3.0  4.0

# Exercise 3
* Create a 5 by 8 random array called *B* using **randn**.
* Find the elements of *B* that are less than 0.2.
* Retrieve the number of rows and columns of *B*.
* Multiply every element of *B* by 3 and assign that to a new array called *C*.
* Sort each row of *C* in ascending order.

In this lesson we covered:
* Single and multi-dimensional arrays.
* Array indexing.
* Applying functions to arrays.