# III. Working with arrays

Julia has built-in functions that can be used to create arrays of random numbers. We can use the `rand` function to generate random floats between 0 and 1.

In [1]:
a = rand(20);
println(a)

[0.19927441672995716, 0.5995918327449121, 0.3141570026895182, 0.4446245154559061, 0.1495385302183222, 0.12771791317770165, 0.6479098707621335, 0.16261916628339923, 0.044064284343234394, 0.23051503533847573, 0.763469665315854, 0.7398896139733794, 0.6270256801833655, 0.3238792421957988, 0.8440816260527113, 0.03815436074199585, 0.3660353643894211, 0.4110789499291604, 0.3905430238564215, 0.07163177855466774]


The `rand` function can be used to sample from an arbitrary set of numbers. Here we sample three values from the values 1 through 20.

In [2]:
rand(1:20, 3)

3-element Vector{Int64}:
 14
 14
 14

Here we use indexing to get the first three elements of __a__.

In [3]:
a[1:3]

3-element Vector{Float64}:
 0.19927441672995716
 0.5995918327449121
 0.3141570026895182

The __end__ keyword can be used to go to the last element along the dimension. The following will get the elements of __a__ starting from index 14 to the end.

In [4]:
a[14:end]

7-element Vector{Float64}:
 0.3238792421957988
 0.8440816260527113
 0.03815436074199585
 0.3660353643894211
 0.4110789499291604
 0.3905430238564215
 0.07163177855466774

You can use a stride index to get skip over elements in the array. For example to get every 2nd element of __a__ starting with the second element.

In [5]:
println(a[2:2:end])

[0.5995918327449121, 0.4446245154559061, 0.12771791317770165, 0.16261916628339923, 0.23051503533847573, 0.7398896139733794, 0.3238792421957988, 0.03815436074199585, 0.4110789499291604, 0.07163177855466774]


You can use `length` to get the number of elements in the array:

In [6]:
length(a)

20

In Julia, you'll likely often be working with multidimensional arrays. Multidimensional arrays have a fixed size.

In [7]:
A = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

Generating random matrices and indexing works the same as before. Below we generate an 8 by 10 matrix of random numbers each distributed according to a standard normal distribution.

In [8]:
A = randn(8, 10)

8×10 Matrix{Float64}:
  0.973697   0.812296    0.490786  …  -1.68223    0.34287      1.06284
  1.7321     0.311126   -0.179409      1.43486   -1.30827     -0.148748
 -0.45186    0.144392   -0.581856     -1.16749    0.00404931   0.339289
 -0.222257  -0.0443037   0.806962      1.29716   -0.218827    -1.13649
  0.594657  -0.310453    0.266167      0.524631  -1.3974      -1.25448
  0.67643   -1.67176     1.23838   …   0.611056  -0.909847    -1.29287
  2.28001    0.4196     -1.24784      -0.870307  -1.12289     -1.13253
  0.636739  -1.46484    -2.11761      -1.0498    -0.768066     0.323589

If we wanted all the rows but only columns 6 through 10 from our matrix __A__:

In [9]:
A[:, 6:10]

8×5 Matrix{Float64}:
  0.434399    0.178926  -1.68223    0.34287      1.06284
  0.213584    0.170761   1.43486   -1.30827     -0.148748
  0.898987    1.0996    -1.16749    0.00404931   0.339289
 -0.764447   -1.10217    1.29716   -0.218827    -1.13649
 -0.182708   -0.627109   0.524631  -1.3974      -1.25448
 -1.57946     1.8385     0.611056  -0.909847    -1.29287
 -1.24615    -0.717542  -0.870307  -1.12289     -1.13253
  0.0038362  -1.59851   -1.0498    -0.768066     0.323589

You can also use boolean indexing to extract elements. Here a random 8 x 10 matrix of booleans is generated:

In [10]:
mask = rand(Bool, 8, 10)

8×10 Matrix{Bool}:
 0  1  1  1  1  1  0  1  1  1
 1  1  1  1  1  0  0  1  1  1
 0  0  1  1  0  0  1  1  0  0
 1  0  1  1  1  0  1  1  1  1
 1  0  1  1  0  1  0  1  1  1
 1  0  1  1  1  1  1  0  0  1
 1  0  0  1  1  0  0  0  1  1
 0  1  1  0  0  1  0  0  1  1

The following statment will return the elements of __A__ that correspond to the elemnts of *mask* that have an entry of *true*.

In [11]:
A[mask]

52-element Vector{Float64}:
  1.732100772312294
 -0.22225660721625645
  0.5946572403707867
  0.676429639324167
  2.280012531511149
  0.812295735452236
  0.31112636227091894
 -1.4648393961749453
  0.49078555170277244
 -0.17940917289358693
 -0.5818556189707039
  0.8069622896871417
  0.26616725042596934
  ⋮
 -1.3082735475653529
 -0.21882717092901138
 -1.3974026473613164
 -1.1228902333754627
 -0.7680656821970078
  1.0628375960734013
 -0.14874801850928454
 -1.1364907862561782
 -1.2544847974329836
 -1.2928677432882052
 -1.1325283148660696
  0.3235886768723595

So if you wanted to return the elements of __A__ that were, say, greater than zero you could do something like the following:

In [12]:
A .> 0

8×10 BitMatrix:
 1  1  1  1  0  1  1  0  1  1
 1  1  0  1  0  1  1  1  0  0
 0  1  0  0  1  1  1  0  1  1
 0  0  1  1  0  0  0  1  0  0
 1  0  1  0  1  0  0  1  0  0
 1  0  1  1  1  0  1  1  0  0
 1  1  0  1  0  0  0  0  0  0
 1  0  0  0  0  1  0  0  0  1

In [13]:
A[A .> 0]

39-element Vector{Float64}:
 0.9736972219551492
 1.732100772312294
 0.5946572403707867
 0.676429639324167
 2.280012531511149
 0.6367391000387295
 0.812295735452236
 0.31112636227091894
 0.14439197390354283
 0.41960018101231866
 0.49078555170277244
 0.8069622896871417
 0.26616725042596934
 ⋮
 0.17076051361363173
 1.099596480767417
 1.8385039189955548
 1.434862939520989
 1.2971625645035785
 0.5246310471871164
 0.6110562571010552
 0.34287046129876875
 0.004049308790014412
 1.0628375960734013
 0.3392891993682771
 0.3235886768723595

Note the dot notation used above which is necessary here to do an element-wise comparison.

One thing to be aware of when you do an assignment with arrays is that the new array is actually a *view* of the original array.

In [14]:
B = A

8×10 Matrix{Float64}:
  0.973697   0.812296    0.490786  …  -1.68223    0.34287      1.06284
  1.7321     0.311126   -0.179409      1.43486   -1.30827     -0.148748
 -0.45186    0.144392   -0.581856     -1.16749    0.00404931   0.339289
 -0.222257  -0.0443037   0.806962      1.29716   -0.218827    -1.13649
  0.594657  -0.310453    0.266167      0.524631  -1.3974      -1.25448
  0.67643   -1.67176     1.23838   …   0.611056  -0.909847    -1.29287
  2.28001    0.4196     -1.24784      -0.870307  -1.12289     -1.13253
  0.636739  -1.46484    -2.11761      -1.0498    -0.768066     0.323589

In [15]:
isequal(B, A)   #use isequal when comparisons involve floats

true

The `===` tests if __B__ and __A__ point to the same location in memory:

In [16]:
B === A

true

Now let's change some elements of __B__. What do you think will happen to __A__?

In [17]:
B[1, 1:end] .= 999;

In [18]:
B

8×10 Matrix{Float64}:
 999.0       999.0        999.0       …  999.0         999.0
   1.7321      0.311126    -0.179409      -1.30827      -0.148748
  -0.45186     0.144392    -0.581856       0.00404931    0.339289
  -0.222257   -0.0443037    0.806962      -0.218827     -1.13649
   0.594657   -0.310453     0.266167      -1.3974       -1.25448
   0.67643    -1.67176      1.23838   …   -0.909847     -1.29287
   2.28001     0.4196      -1.24784       -1.12289      -1.13253
   0.636739   -1.46484     -2.11761       -0.768066      0.323589

Note that even though we changed the elements of __B__ the elements of the original array __A__ also changed.

In [19]:
A

8×10 Matrix{Float64}:
 999.0       999.0        999.0       …  999.0         999.0
   1.7321      0.311126    -0.179409      -1.30827      -0.148748
  -0.45186     0.144392    -0.581856       0.00404931    0.339289
  -0.222257   -0.0443037    0.806962      -0.218827     -1.13649
   0.594657   -0.310453     0.266167      -1.3974       -1.25448
   0.67643    -1.67176      1.23838   …   -0.909847     -1.29287
   2.28001     0.4196      -1.24784       -1.12289      -1.13253
   0.636739   -1.46484     -2.11761       -0.768066      0.323589

If you want to avoid this behavior then you can use the `copy` function to make a copy of the original array:

In [20]:
C = copy(A);

In [21]:
isequal(C, A)

true

In [22]:
C === A

false

What the above shows is that __C__ points to a different location in memory than __A__, so you can change __C__ without affecting __A__.

Let's move on and look at some basic functions and operations that you can with arrays.

To check the dimension of an array you can use the `ndims` function:

In [23]:
A = randn(8, 10)

8×10 Matrix{Float64}:
  0.316048  -1.36823     0.157945  …  -0.764642    1.38092    -0.727657
  0.843301  -0.756339   -0.917414     -1.29919    -0.58761     0.17818
  0.360375  -0.335528    0.579074     -0.610191   -0.880904    0.9426
 -0.736977  -0.895995   -0.593636      1.77534    -0.320131    0.38059
 -1.12776    0.0374451   0.673967     -0.282021   -0.0330874   0.399979
 -1.89336    0.72704     1.98249   …   0.705806   -1.4006     -0.125531
  0.597657  -0.421783    0.997781     -1.29215    -2.94024     0.271466
 -1.64747    1.50509     0.755699      0.0666121  -0.481064    1.56306

In [24]:
ndims(A)

2

To get the number of rows and columns use `size`:

In [25]:
size(A)

(8, 10)

Ae before `length` returns the number of elements in the matrix.

In [26]:
length(A)

80

The `reshape` function will change the shape of the array:

The `zeros` function is available to create a matrix of zeros; the `fill` function can create a matrix with an arbitrary element.

In [27]:
zeros(4, 5)

4×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [28]:
fill("foo", 4, 5)

4×5 Matrix{String}:
 "foo"  "foo"  "foo"  "foo"  "foo"
 "foo"  "foo"  "foo"  "foo"  "foo"
 "foo"  "foo"  "foo"  "foo"  "foo"
 "foo"  "foo"  "foo"  "foo"  "foo"

As mentioned before, if you want to do element-wise operations on an array you use dot notation. To demonstrate let's first generate a random matrix.

In [29]:
A = randn(4, 5)

4×5 Matrix{Float64}:
  1.14584    -2.88168   -1.00279    0.250774   0.201406
 -2.1494      0.223862   0.863263  -1.35843   -1.4132
 -0.439279    0.954469   0.978425  -0.869607  -1.0674
 -0.0993304  -0.824938  -0.644342   0.243111   0.800969

Now we square every element of __A__ using the dot syntax:

In [30]:
A.^2

4×5 Matrix{Float64}:
 1.31294     8.30406    1.00559   0.0628875  0.0405645
 4.61993     0.0501143  0.745223  1.84533    1.99715
 0.192966    0.911012   0.957316  0.756217   1.13935
 0.00986652  0.680523   0.415177  0.0591028  0.641551

Similarly we can do element-wise division between two matrices. Below we can create a new random matrix __B__ then divide the elements of __A__ by their corresponding elements in __B__.

In [31]:
B =  randn(4, 5)

4×5 Matrix{Float64}:
 -0.586188  -1.04906    0.666724   0.00120521  -0.00571764
  0.202614  -0.158226  -0.724277  -1.72377     -0.196249
  1.40491   -0.547284  -1.06172   -1.60088      0.530513
  1.85506   -1.02089    0.973248  -0.0152956    0.934886

In [32]:
A ./ B

4×5 Matrix{Float64}:
  -1.95472     2.74692   -1.50405   208.075     -35.2254
 -10.6083     -1.41483   -1.1919      0.788058    7.20106
  -0.312675   -1.74401   -0.921548    0.543205   -2.01202
  -0.0535455   0.808061  -0.662053  -15.8942      0.856756

There are a lot of basic functions that can be applied to arrays: `sum`, `mean`, `sort`, etc.

In [33]:
A = [1 -1 2 3; 4 -3 1 0; 7 -3 -3 2]

3×4 Matrix{Int64}:
 1  -1   2  3
 4  -3   1  0
 7  -3  -3  2

To sum all the elements of **A**:

In [34]:
A

3×4 Matrix{Int64}:
 1  -1   2  3
 4  -3   1  0
 7  -3  -3  2

In [35]:
sum(A)

10

In [36]:
sum(A, dims = 1) #sums each column

1×4 Matrix{Int64}:
 12  -7  0  5

In [37]:
sum(A, dims = 2) #sums each row

3×1 Matrix{Int64}:
 5
 2
 3

# Exercise 3
* Create a 5 by 8 random array called *B* using **randn**.
* Find the elements of *B* that are less than 0.2.
* Retrieve the number of rows and columns of *B*.
* Multiply every element of *B* by 3 and assign that to a new array called *C*.
* Sort each row of *C* in ascending order.

In this lesson we covered:
* Single and multi-dimensional arrays.
* Array indexing.
* Applying functions to arrays.