# III. Working with arrays

Julia has built-in functions that can be used to create arrays of random numbers. We can use the `rand` function to generate random floats between 0 and 1.

In [1]:
a = rand(20);
println(a)

[0.4660981148138049, 0.258749901395646, 0.9721783266817419, 0.4717384593440128, 0.6591903941482612, 0.708907890556231, 0.3725024212529774, 0.07680706843600082, 0.34178412903671895, 0.5411231742443114, 0.3164062053083231, 0.6557893629367703, 0.009502522457330964, 0.6493643975151135, 0.41391698055909265, 0.18743145382574555, 0.2549600996121155, 0.04592092180944651, 0.6003033250855557, 0.6118436539964646]


The `rand` function can be used to sample from an arbitrary set of numbers. Here we sample three values from the values 1 through 20.

In [2]:
rand(1:20, 3)

3-element Vector{Int64}:
  1
  4
 17

Here we use indexing to get the first three elements of __a__.

In [3]:
a[1:3]

3-element Vector{Float64}:
 0.4660981148138049
 0.258749901395646
 0.9721783266817419

The __end__ keyword can be used to go to the last element along the dimension. The following will get the elements of __a__ starting from index 14 to the end.

In [4]:
a[14:end]

7-element Vector{Float64}:
 0.6493643975151135
 0.41391698055909265
 0.18743145382574555
 0.2549600996121155
 0.04592092180944651
 0.6003033250855557
 0.6118436539964646

You can use a stride index to get skip over elements in the array. For example to get every 2nd element of __a__ starting with the second element.

In [5]:
println(a[2:2:end])

[0.258749901395646, 0.4717384593440128, 0.708907890556231, 0.07680706843600082, 0.5411231742443114, 0.6557893629367703, 0.6493643975151135, 0.18743145382574555, 0.04592092180944651, 0.6118436539964646]


You can use `length` to get the number of elements in the array:

In [6]:
length(a)

20

In Julia, you'll likely often be working with multidimensional arrays. Multidimensional arrays have a fixed size.

In [7]:
A = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

Generating random matrices and indexing works the same as before. Below we generate an 8 by 10 matrix of random numbers each distributed according to a standard normal distribution.

In [8]:
A = randn(8, 10)

8×10 Matrix{Float64}:
 -0.355498    0.390379  -0.335696  …  -0.851937     0.659678   0.431441
  0.298782   -0.861078  -0.165863      0.869274     0.142576   0.0934272
  0.0856952   0.667525  -1.0695       -1.11277     -1.61006    0.58925
  1.10653     0.713133  -0.789897     -0.749046    -0.341754   0.411418
 -0.0438247  -1.17669   -1.64958      -0.282738    -1.5237     0.484183
 -0.505133    1.06316   -0.216403  …  -0.174368     0.209036   0.385284
  0.703956    1.18219    1.01599       0.715476    -1.28158   -0.0762283
  0.46209    -0.655671   0.530031     -0.00418628   2.31305    0.614096

If we wanted all the rows but only columns 6 through 10 from our matrix __A__:

In [9]:
A[:, 6:10]

8×5 Matrix{Float64}:
 -0.207179   0.32398   -0.851937     0.659678   0.431441
  2.06717    0.794282   0.869274     0.142576   0.0934272
 -1.15624   -0.552023  -1.11277     -1.61006    0.58925
  0.818427   1.36385   -0.749046    -0.341754   0.411418
 -1.00825    1.2028    -0.282738    -1.5237     0.484183
  0.612498   2.3267    -0.174368     0.209036   0.385284
 -0.331876  -2.02105    0.715476    -1.28158   -0.0762283
 -1.99851    1.67513   -0.00418628   2.31305    0.614096

You can also use boolean indexing to extract elements. Here a random 8 x 10 matrix of booleans is generated:

In [10]:
mask = rand(Bool, 8, 10)

8×10 Matrix{Bool}:
 0  0  0  0  0  0  1  0  1  1
 0  1  1  0  0  1  1  0  0  1
 1  1  1  0  1  1  0  0  0  1
 0  0  1  1  1  1  0  1  0  0
 1  1  1  1  1  1  0  1  0  1
 0  1  0  1  0  1  1  1  0  0
 0  0  1  0  0  1  1  0  0  1
 1  1  1  1  0  0  1  0  0  1

The following statment will return the elements of __A__ that correspond to the elemnts of *mask* that have an entry of *true*.

In [11]:
A[mask]

42-element Vector{Float64}:
  0.08569524191116054
 -0.043824726113830044
  0.4620900109588872
 -0.8610782374822157
  0.667524628740573
 -1.1766887108006634
  1.0631620460418445
 -0.6556705643122412
 -0.16586335252100196
 -1.0695011508976193
 -0.7898965826484503
 -1.6495843927410507
  1.0159928677072467
  ⋮
 -2.0210534636372754
  1.6751280591226032
 -0.7490463986370255
 -0.28273788701830377
 -0.17436765178390115
  0.659677729983345
  0.43144142757161147
  0.09342715271460794
  0.5892498057550751
  0.4841825956385701
 -0.07622828077869469
  0.6140963584813235

So if you wanted to return the elements of __A__ that were, say, greater than zero you could do something like the following:

In [12]:
A .> 0

8×10 BitMatrix:
 0  1  0  1  1  0  1  0  1  1
 1  0  0  0  0  1  1  1  1  1
 1  1  0  0  1  0  0  0  0  1
 1  1  0  0  1  1  1  0  0  1
 0  0  0  0  1  0  1  0  0  1
 0  1  0  0  1  1  1  0  1  1
 1  1  1  0  0  0  0  1  0  0
 1  0  1  1  1  0  1  0  1  1

In [13]:
A[A .> 0]

42-element Vector{Float64}:
 0.2987822118320379
 0.08569524191116054
 1.1065340517212878
 0.7039563237994257
 0.4620900109588872
 0.39037876519315484
 0.667524628740573
 0.7131334671927712
 1.0631620460418445
 1.1821920852986016
 1.0159928677072467
 0.5300309936660865
 0.03935927747090346
 ⋮
 0.7154760079761578
 0.659677729983345
 0.14257572802156943
 0.20903641117055347
 2.3130507190709917
 0.43144142757161147
 0.09342715271460794
 0.5892498057550751
 0.4114175343620462
 0.4841825956385701
 0.3852841065262688
 0.6140963584813235

Note the dot notation used above which is necessary here to do an element-wise comparison.

One thing to be aware of when you do an assignment with arrays is that the new array is actually a *view* of the original array.

In [14]:
B = A

8×10 Matrix{Float64}:
 -0.355498    0.390379  -0.335696  …  -0.851937     0.659678   0.431441
  0.298782   -0.861078  -0.165863      0.869274     0.142576   0.0934272
  0.0856952   0.667525  -1.0695       -1.11277     -1.61006    0.58925
  1.10653     0.713133  -0.789897     -0.749046    -0.341754   0.411418
 -0.0438247  -1.17669   -1.64958      -0.282738    -1.5237     0.484183
 -0.505133    1.06316   -0.216403  …  -0.174368     0.209036   0.385284
  0.703956    1.18219    1.01599       0.715476    -1.28158   -0.0762283
  0.46209    -0.655671   0.530031     -0.00418628   2.31305    0.614096

In [15]:
isequal(B, A)   #use isequal when comparisons involve floats

true

The `===` tests if __B__ and __A__ point to the same location in memory:

In [16]:
B === A

true

Now let's change some elements of __B__. What do you think will happen to __A__?

In [17]:
B[1, 1:end] .= 999;

In [18]:
B

8×10 Matrix{Float64}:
 999.0        999.0       999.0       …  999.0       999.0
   0.298782    -0.861078   -0.165863       0.142576    0.0934272
   0.0856952    0.667525   -1.0695        -1.61006     0.58925
   1.10653      0.713133   -0.789897      -0.341754    0.411418
  -0.0438247   -1.17669    -1.64958       -1.5237      0.484183
  -0.505133     1.06316    -0.216403  …    0.209036    0.385284
   0.703956     1.18219     1.01599       -1.28158    -0.0762283
   0.46209     -0.655671    0.530031       2.31305     0.614096

Note that even though we changed the elements of __B__ the elements of the original array __A__ also changed.

In [19]:
A

8×10 Matrix{Float64}:
 999.0        999.0       999.0       …  999.0       999.0
   0.298782    -0.861078   -0.165863       0.142576    0.0934272
   0.0856952    0.667525   -1.0695        -1.61006     0.58925
   1.10653      0.713133   -0.789897      -0.341754    0.411418
  -0.0438247   -1.17669    -1.64958       -1.5237      0.484183
  -0.505133     1.06316    -0.216403  …    0.209036    0.385284
   0.703956     1.18219     1.01599       -1.28158    -0.0762283
   0.46209     -0.655671    0.530031       2.31305     0.614096

If you want to avoid this behavior then you can use the `copy` function to make a copy of the original array:

In [20]:
C = copy(A);

In [21]:
isequal(C, A)

true

In [22]:
C === A

false

What the above shows is that __C__ points to a different location in memory than __A__, so you can change __C__ without affecting __A__.

Let's move on and look at some basic functions and operations that you can with arrays.

To check the dimension of an array you can use the `ndims` function:

In [23]:
A = randn(8, 10)

8×10 Matrix{Float64}:
  0.851655   -0.336184   -0.551639  …  -2.2881    -0.860342   0.495898
  0.779324   -0.41162     0.469769      1.01999   -0.489706  -1.54691
 -0.0653381   0.432461    1.47853      -0.550678  -1.73238   -1.42522
 -1.43632     1.27308     0.486607     -1.26745    0.582721   1.41277
 -0.425849    0.575888    1.16204      -1.1074    -0.19815    1.15737
  1.58684    -1.3536     -0.155946  …   0.348709  -0.67193    1.48505
  0.205722    0.326895    0.804621     -1.17124    0.110225  -0.134096
  0.581264    0.0303504   0.919418     -1.67499   -0.270776   0.424266

In [24]:
ndims(A)

2

To get the number of rows and columns use `size`:

In [25]:
size(A)

(8, 10)

Ae before `length` returns the number of elements in the matrix.

In [26]:
length(A)

80

The `reshape` function will change the shape of the array:

The `zeros` function is available to create a matrix of zeros; the `fill` function can create a matrix with an arbitrary element.

In [27]:
zeros(4, 5)

4×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [28]:
fill("foo", 4, 5)

4×5 Matrix{String}:
 "foo"  "foo"  "foo"  "foo"  "foo"
 "foo"  "foo"  "foo"  "foo"  "foo"
 "foo"  "foo"  "foo"  "foo"  "foo"
 "foo"  "foo"  "foo"  "foo"  "foo"

As mentioned before, if you want to do element-wise operations on an array you use dot notation. To demonstrate let's first generate a random matrix.

In [29]:
A = randn(4, 5)

4×5 Matrix{Float64}:
 -0.84056    0.307935  -1.13092   0.184802   0.0047621
  0.332732  -0.973966   1.06585   0.675855   0.12169
  0.947012   0.560921   1.14328  -0.0754592  0.406881
 -0.96819    0.371349  -0.76365   1.20987    1.62662

Now we square every element of __A__ using the dot syntax:

In [30]:
A.^2

4×5 Matrix{Float64}:
 0.706542  0.0948241  1.27898   0.0341518   2.26776e-5
 0.11071   0.948609   1.13604   0.45678     0.0148084
 0.896831  0.314632   1.30709   0.00569409  0.165552
 0.937393  0.1379     0.583162  1.46379     2.6459

Similarly we can do element-wise division between two matrices. Below we can create a new random matrix __B__ then divide the elements of __A__ by their corresponding elements in __B__.

In [31]:
B =  randn(4, 5)

4×5 Matrix{Float64}:
 -1.56714   0.124203   0.131469  -1.24547   1.10425
  0.740822  2.0477     0.867374  -0.051259  0.00212268
 -0.844861  1.53316    0.937298  -0.958591  0.460477
 -1.34959   2.16777   -0.994619   1.3733    0.0548412

In [32]:
A ./ B

4×5 Matrix{Float64}:
  0.536367   2.47928   -8.60217    -0.14838     0.00431252
  0.449139  -0.475639   1.22883   -13.1851     57.3283
 -1.12091    0.365861   1.21976     0.0787188   0.883608
  0.717397   0.171305   0.767782    0.880996   29.6606

There are a lot of basic functions that can be applied to arrays: `sum`, `mean`, `sort`, etc.

In [33]:
A = [1 -1 2 3; 4 -3 1 0; 7 -3 -3 2]

3×4 Matrix{Int64}:
 1  -1   2  3
 4  -3   1  0
 7  -3  -3  2

To sum all the elements of **A**:

In [34]:
A

3×4 Matrix{Int64}:
 1  -1   2  3
 4  -3   1  0
 7  -3  -3  2

In [35]:
sum(A)

10

In [36]:
sum(A, dims = 1) #sums each column

1×4 Matrix{Int64}:
 12  -7  0  5

In [37]:
sum(A, dims = 2) #sums each row

3×1 Matrix{Int64}:
 5
 2
 3

# Exercise 3
* Create a 5 by 8 random array called *B* using **randn**.
* Find the elements of *B* that are less than 0.2.
* Retrieve the number of rows and columns of *B*.
* Multiply every element of *B* by 3 and assign that to a new array called *C*.
* Sort each row of *C* in ascending order.

In this lesson we covered:
* Single and multi-dimensional arrays.
* Array indexing.
* Applying functions to arrays.